# NEVER commit this to GitHub!
supabase_url = "https://usjzyeqyongwwgpbglkf.supabase.co"
supabase_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzanp5ZXF5b25nd3dncGJnbGtmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3MDk4NDUsImV4cCI6MjA4MDI4NTg0NX0.bhDWAk3P95d6fBY1KGSslkyLWrIS3v9r4ppvLBE03oo"
stripe_public_key = "pk_test_51Sa2bPKaslykU7LoVKy5fjlfFoM5oc1P0SGMNvuItN7PscossTkReuJEGEB91vsWLsGnMT26x8IxGbeyRfamHlcR00Xjw9PksV"
stripe_secret_key = "sk_test_51Sa2bPKaslykU7Lo2cQ0FUFVIjC5ca08pER53uAYMuDfPxIjG3VMNShp0Zy1CBDNhJBZazEDVqxNRhyk5fRIGPEk001G5eqltZ"
qstash_token = "yJVc2VySUQiOiI2N2QxNDVhMi0xNGRhLTQ0YzAtYTQ5OC1mYjY4NmY5MTNiMDIiLCJQYXNzd29yZCI6ImMzOTI3MDliY2FiYTQ0ZDA4MWMyZWQ2MWUxNmQ2MmVjIn0="
qstash_current_signing_key = "sig_6sBHXqgT4h7arvLv6cUhfFaQJRgx"
qstash_next_signing_key = "sig_5YMZjeYXrPqDdikyS8z33rep8LGF"